// ============================================
// ScreenAI — Internationalization (i18n)
// ============================================

export type UILanguage = 'en' | 'fr' | 'es' | 'de' | 'zh' | 'ja' | 'ko';

export interface Translations {
  // Sidebar
  captureScreen: string;
  discussion: string;
  project: string;
  searchPlaceholder: string;
  projects: string;
  discussions: string;
  noProject: string;
  noDiscussion: string;
  settings: string;
  conversations: string;

  // Context menu
  rename: string;
  moveToProject: string;
  delete: string;

  // Welcome
  welcomeTitle: string;
  welcomeDesc: string;
  captureMyScreen: string;
  fullscreen: string;
  zone: string;

  // Settings
  settingsTitle: string;
  aiSection: string;
  defaultAI: string;
  responseLang: string;
  appearance: string;
  theme: string;
  light: string;
  dark: string;
  auto: string;
  accentColor: string;
  systemPrompt: string;
  systemPromptDesc: string;
  shortcuts: string;
  captureFullscreen: string;
  captureZone: string;
  highlight: string;
  search: string;
  account: string;
  localMode: string;
  localModeDesc: string;
  logOut: string;
  save: string;
  saved: string;
  apiKey: string;
  model: string;
  serverUrl: string;

  // Chat
  inputPlaceholder: string;
  captureAttached: string;
  freeRequests: string;
  configureApiKey: string;
  errorContact: string;

  // Modals
  newProject: string;
  newDiscussion: string;
  renameTo: string;
  editProject: string;
  confirm: string;
  name: string;
  description: string;
  aiInstructions: string;
  aiInstructionsPlaceholder: string;
  attachToProject: string;
  noneFreeTalk: string;
  ai: string;
  cancel: string;
  create: string;
  saveName: string;
  titleOptional: string;
  titleAutoGenerated: string;
  deleteConfirm: string;
  deleteProjectMsg: (name: string, count: number) => string;
  deleteProjectMsgSimple: (name: string) => string;
  deleteConvMsg: (title: string) => string;
  disconnectConfirm: string;

  // Language prompts
  langPrompt: string;
}

const en: Translations = {
  // Sidebar
  captureScreen: "Capture Screen",
  discussion: "Discussion",
  project: "Project",
  searchPlaceholder: "Search...",
  projects: "Projects",
  discussions: "Discussions",
  noProject: "No projects",
  noDiscussion: "No discussions",
  settings: "Settings",
  conversations: "conversations",

  // Context menu
  rename: "Rename",
  moveToProject: "Move to project",
  delete: "Delete",

  // Welcome
  welcomeTitle: "Welcome to ScreenAI",
  welcomeDesc: "Capture your screen, annotate, and ask any AI — without leaving your workflow.",
  captureMyScreen: "Capture my screen",
  fullscreen: "Fullscreen",
  zone: "Region",

  // Settings
  settingsTitle: "Settings",
  aiSection: "Artificial Intelligence",
  defaultAI: "Default AI",
  responseLang: "Response language",
  appearance: "Appearance",
  theme: "Theme",
  light: "Light",
  dark: "Dark",
  auto: "Auto",
  accentColor: "Accent color",
  systemPrompt: "System Prompt",
  systemPromptDesc: "Customize the default AI behavior for all conversations.",
  shortcuts: "Keyboard Shortcuts",
  captureFullscreen: "Fullscreen capture",
  captureZone: "Region capture",
  highlight: "Highlight",
  search: "Search",
  account: "Account",
  localMode: "Local mode",
  localModeDesc: "Data is stored locally",
  logOut: "Log out",
  save: "Save",
  saved: "Saved!",
  apiKey: "API KEY",
  model: "MODEL",
  serverUrl: "SERVER URL",

  // Chat
  inputPlaceholder: "Describe your problem or ask a question...",
  captureAttached: "Capture attached",
  freeRequests: "free requests",
  configureApiKey: "Configure your API key in Settings to use this provider.",
  errorContact: "Unable to contact the AI provider.",

  // Modals
  newProject: "New Project",
  newDiscussion: "New Discussion",
  renameTo: "Rename",
  editProject: "Edit Project",
  confirm: "Confirm",
  name: "NAME",
  description: "DESCRIPTION",
  aiInstructions: "AI INSTRUCTIONS",
  aiInstructionsPlaceholder: "You are an expert in...",
  attachToProject: "ATTACH TO PROJECT",
  noneFreeTalk: "None (free talk)",
  ai: "AI PROVIDER",
  cancel: "Cancel",
  create: "Create",
  saveName: "Save",
  titleOptional: "TITLE (optional)",
  titleAutoGenerated: "Will be auto-generated",
  deleteConfirm: "Delete",
  deleteProjectMsg: (name, count) =>
    `Delete project "${name}" and its ${count} conversation(s)? Conversations will be converted to free discussions.`,
  deleteProjectMsgSimple: (name) => `Delete project "${name}"?`,
  deleteConvMsg: (title) => `Delete conversation "${title}"?`,
  disconnectConfirm: "Do you want to log out?",

  // Language prompts
  langPrompt: "Always respond in English.",
};

const fr: Translations = {
  // Sidebar
  captureScreen: "Capturer l'écran",
  discussion: "Discussion",
  project: "Projet",
  searchPlaceholder: "Rechercher...",
  projects: "Projets",
  discussions: "Discussions",
  noProject: "Aucun projet",
  noDiscussion: "Aucune discussion",
  settings: "Paramètres",
  conversations: "conversations",

  // Context menu
  rename: "Renommer",
  moveToProject: "Déplacer vers un projet",
  delete: "Supprimer",

  // Welcome
  welcomeTitle: "Bienvenue sur ScreenAI",
  welcomeDesc: "Capturez votre écran, annotez, et demandez à n'importe quelle IA — sans quitter votre workflow.",
  captureMyScreen: "Capturer mon écran",
  fullscreen: "Plein écran",
  zone: "Zone",

  // Settings
  settingsTitle: "Paramètres",
  aiSection: "Intelligence artificielle",
  defaultAI: "IA par défaut",
  responseLang: "Langue de réponse",
  appearance: "Apparence",
  theme: "Thème",
  light: "Clair",
  dark: "Sombre",
  auto: "Auto",
  accentColor: "Couleur d'accent",
  systemPrompt: "Prompt système",
  systemPromptDesc: "Personnalise le comportement par défaut de l'IA pour toutes les conversations.",
  shortcuts: "Raccourcis clavier",
  captureFullscreen: "Capture plein écran",
  captureZone: "Capture zone",
  highlight: "Surligner",
  search: "Rechercher",
  account: "Compte",
  localMode: "Mode local",
  localModeDesc: "Les données sont stockées localement",
  logOut: "Se déconnecter",
  save: "Sauvegarder",
  saved: "Sauvegardé !",
  apiKey: "CLÉ API",
  model: "MODÈLE",
  serverUrl: "URL SERVEUR",

  // Chat
  inputPlaceholder: "Décris ton problème ou pose ta question...",
  captureAttached: "Capture jointe",
  freeRequests: "requêtes gratuites",
  configureApiKey: "Configure ta clé API dans les paramètres pour utiliser ce provider.",
  errorContact: "Impossible de contacter le provider IA.",

  // Modals
  newProject: "Nouveau projet",
  newDiscussion: "Nouvelle discussion",
  renameTo: "Renommer",
  editProject: "Modifier le projet",
  confirm: "Confirmer",
  name: "NOM",
  description: "DESCRIPTION",
  aiInstructions: "INSTRUCTIONS POUR L'IA",
  aiInstructionsPlaceholder: "Tu es un expert en...",
  attachToProject: "RATTACHER À UN PROJET",
  noneFreeTalk: "Aucun (discussion libre)",
  ai: "INTELLIGENCE ARTIFICIELLE",
  cancel: "Annuler",
  create: "Créer",
  saveName: "Sauvegarder",
  titleOptional: "TITRE (optionnel)",
  titleAutoGenerated: "Sera généré automatiquement",
  deleteConfirm: "Supprimer",
  deleteProjectMsg: (name, count) =>
    `Supprimer le projet "${name}" et ses ${count} conversation(s) ? Les conversations seront converties en discussions libres.`,
  deleteProjectMsgSimple: (name) => `Supprimer le projet "${name}" ?`,
  deleteConvMsg: (title) => `Supprimer la conversation "${title}" ?`,
  disconnectConfirm: "Voulez-vous vous déconnecter ?",

  // Language prompts
  langPrompt: "Réponds toujours en français.",
};

const es: Translations = {
  ...en,
  captureScreen: "Capturar pantalla",
  welcomeTitle: "Bienvenido a ScreenAI",
  welcomeDesc: "Captura tu pantalla, anota y pregunta a cualquier IA — sin salir de tu flujo de trabajo.",
  langPrompt: "Responde siempre en español.",
};

const de: Translations = {
  ...en,
  captureScreen: "Bildschirm aufnehmen",
  welcomeTitle: "Willkommen bei ScreenAI",
  welcomeDesc: "Nehmen Sie Ihren Bildschirm auf, kommentieren Sie und fragen Sie jede KI — ohne Ihren Workflow zu verlassen.",
  langPrompt: "Antworte immer auf Deutsch.",
};

const zh: Translations = {
  ...en,
  captureScreen: "截取屏幕",
  discussion: "对话",
  project: "项目",
  searchPlaceholder: "搜索...",
  projects: "项目",
  discussions: "对话",
  noProject: "暂无项目",
  noDiscussion: "暂无对话",
  settings: "设置",
  conversations: "对话",
  welcomeTitle: "欢迎使用 ScreenAI",
  welcomeDesc: "截取屏幕，标注，向任何AI提问 — 无需离开您的工作流。",
  captureMyScreen: "截取我的屏幕",
  fullscreen: "全屏",
  zone: "区域",
  langPrompt: "请始终用中文回答。",
};

const ja: Translations = {
  ...en,
  captureScreen: "画面をキャプチャ",
  discussion: "会話",
  project: "プロジェクト",
  searchPlaceholder: "検索...",
  projects: "プロジェクト",
  discussions: "会話",
  noProject: "プロジェクトなし",
  noDiscussion: "会話なし",
  settings: "設定",
  conversations: "会話",
  welcomeTitle: "ScreenAI へようこそ",
  welcomeDesc: "画面をキャプチャし、注釈を付け、あらゆるAIに質問 — ワークフローを離れることなく。",
  captureMyScreen: "画面をキャプチャ",
  fullscreen: "フルスクリーン",
  zone: "領域",
  langPrompt: "常に日本語で回答してください。",
};

const ko: Translations = {
  ...en,
  captureScreen: "화면 캡처",
  discussion: "대화",
  project: "프로젝트",
  searchPlaceholder: "검색...",
  projects: "프로젝트",
  discussions: "대화",
  noProject: "프로젝트 없음",
  noDiscussion: "대화 없음",
  settings: "설정",
  conversations: "대화",
  welcomeTitle: "ScreenAI에 오신 것을 환영합니다",
  welcomeDesc: "화면을 캡처하고 주석을 달고 모든 AI에게 질문하세요 — 워크플로를 떠나지 않고.",
  captureMyScreen: "화면 캡처",
  fullscreen: "전체 화면",
  zone: "영역",
  langPrompt: "항상 한국어로 답변해 주세요.",
};

const translations: Record<UILanguage, Translations> = { en, fr, es, de, zh, ja, ko };

let currentLang: UILanguage = 'en';

export function setUILanguage(lang: UILanguage) {
  currentLang = lang;
}

export function getUILanguage(): UILanguage {
  return currentLang;
}

export function t(): Translations {
  return translations[currentLang] || translations.en;
}
