// ============================================
// ScreenAI — Modals (project, discussion, rename, confirm)
// ============================================

import { PROVIDER_LABELS, MODEL_OPTIONS, type AIProviderType } from '../../types';
import { t } from './i18n';

// --- Generic Modal ---
function createModal(title: string, bodyHtml: string, onSubmit: (form: HTMLFormElement) => void, submitLabel?: string): HTMLDivElement {
  const i = t();
  const overlay = document.createElement('div');
  overlay.className = 'mov op';
  overlay.innerHTML = `
    <div class="mod">
      <h3>${title}</h3>
      <form>
        ${bodyHtml}
        <div class="mact">
          <button type="button" class="mb mbc" data-cancel>${i.cancel}</button>
          <button type="submit" class="mb mbp">${submitLabel || i.create}</button>
        </div>
      </form>
    </div>
  `;

  const form = overlay.querySelector('form')!;
  const cancelBtn = overlay.querySelector('[data-cancel]')!;

  const close = () => overlay.remove();

  cancelBtn.addEventListener('click', close);
  overlay.addEventListener('click', (e) => {
    if (e.target === overlay) close();
  });

  form.addEventListener('submit', (e) => {
    e.preventDefault();
    onSubmit(form);
    close();
  });

  // Escape closes modal
  const onKey = (e: KeyboardEvent) => {
    if (e.key === 'Escape') { close(); document.removeEventListener('keydown', onKey); }
  };
  document.addEventListener('keydown', onKey);

  document.body.appendChild(overlay);

  // Focus first input
  const firstInput = form.querySelector<HTMLInputElement>('input, textarea');
  if (firstInput) setTimeout(() => firstInput.focus(), 50);

  return overlay;
}

// --- Provider options HTML ---
function providerOptions(selected?: AIProviderType): string {
  return (Object.keys(PROVIDER_LABELS) as AIProviderType[])
    .map(k => `<option value="${k}"${k === selected ? ' selected' : ''}>${PROVIDER_LABELS[k]}</option>`)
    .join('');
}

// --- New Project Modal ---
export interface NewProjectData {
  name: string;
  description: string;
  instructions: string;
  provider: AIProviderType;
}

export function showNewProjectModal(callback: (data: NewProjectData) => void) {
  const i = t();
  createModal(i.newProject, `
    <div class="mf">
      <label>${i.name}</label>
      <input class="minp" name="name" placeholder="My project" required>
    </div>
    <div class="mf">
      <label>${i.description}</label>
      <input class="minp" name="description" placeholder="Short project description">
    </div>
    <div class="mf">
      <label>${i.aiInstructions}</label>
      <textarea class="mta" name="instructions" rows="3" placeholder="${i.aiInstructionsPlaceholder}"></textarea>
    </div>
    <div class="mf">
      <label>${i.ai}</label>
      <select class="msel" name="provider">${providerOptions('claude')}</select>
    </div>
  `, (form) => {
    const fd = new FormData(form);
    callback({
      name: fd.get('name') as string,
      description: fd.get('description') as string || '',
      instructions: fd.get('instructions') as string || '',
      provider: fd.get('provider') as AIProviderType,
    });
  });
}

// --- New Discussion Modal ---
export interface NewConversationData {
  title: string;
  projectId: string;
  provider: AIProviderType;
}

export function showNewConversationModal(
  projects: { id: string; name: string }[],
  callback: (data: NewConversationData) => void
) {
  const i = t();
  const projectOptions = [
    `<option value="">${i.noneFreeTalk}</option>`,
    ...projects.map(p => `<option value="${p.id}">${p.name}</option>`)
  ].join('');

  createModal(i.newDiscussion, `
    <div class="mf">
      <label>${i.titleOptional}</label>
      <input class="minp" name="title" placeholder="${i.titleAutoGenerated}">
    </div>
    <div class="mf">
      <label>${i.attachToProject}</label>
      <select class="msel" name="projectId">${projectOptions}</select>
    </div>
    <div class="mf">
      <label>${i.ai}</label>
      <select class="msel" name="provider">${providerOptions('claude')}</select>
    </div>
  `, (form) => {
    const fd = new FormData(form);
    callback({
      title: fd.get('title') as string || '',
      projectId: fd.get('projectId') as string,
      provider: fd.get('provider') as AIProviderType,
    });
  });
}

// --- Rename Modal ---
export function showRenameModal(currentName: string, callback: (newName: string) => void) {
  const i = t();
  createModal(i.renameTo, `
    <div class="mf">
      <label>${i.name}</label>
      <input class="minp" name="name" value="${currentName.replace(/"/g, '&quot;')}" required>
    </div>
  `, (form) => {
    const fd = new FormData(form);
    callback(fd.get('name') as string);
  }, i.saveName);
}

// --- Edit Project Modal ---
export interface EditProjectData {
  name: string;
  description: string;
  instructions: string;
  provider: AIProviderType;
}

export function showEditProjectModal(
  project: { name: string; description: string; instructions: string; provider: AIProviderType },
  callback: (data: EditProjectData) => void
) {
  const i = t();
  createModal(i.editProject, `
    <div class="mf">
      <label>${i.name}</label>
      <input class="minp" name="name" value="${project.name.replace(/"/g, '&quot;')}" required>
    </div>
    <div class="mf">
      <label>${i.description}</label>
      <input class="minp" name="description" value="${project.description.replace(/"/g, '&quot;')}">
    </div>
    <div class="mf">
      <label>${i.aiInstructions}</label>
      <textarea class="mta" name="instructions" rows="3">${project.instructions}</textarea>
    </div>
    <div class="mf">
      <label>${i.ai}</label>
      <select class="msel" name="provider">${providerOptions(project.provider)}</select>
    </div>
  `, (form) => {
    const fd = new FormData(form);
    callback({
      name: fd.get('name') as string,
      description: fd.get('description') as string || '',
      instructions: fd.get('instructions') as string || '',
      provider: fd.get('provider') as AIProviderType,
    });
  }, i.saveName);
}

// --- Confirmation Modal ---
export function showConfirmModal(message: string, callback: () => void) {
  const i = t();
  createModal(i.confirm, `
    <p style="font-size:13px;color:var(--t2);line-height:1.6;margin-bottom:8px">${message}</p>
  `, () => {
    callback();
  }, i.deleteConfirm);
}
